export interface CaseStudy {
  slug: string;
  client: string;
  category: string;
  duration: string;
  title: string;
  subtitle: string;
  description: string;
  image: string;
  url?: string;
  tech: string[];
  overview: string;
  challenge: string;
  solution: string;
  results: { metric: string; label: string }[];
  deliverables: string[];
  testimonial?: { quote: string; name: string; role: string };
  gallery?: string[];
  highlights?: { label: string; value: string; desc: string }[];
  accentColor: string;
}

export const caseStudies: CaseStudy[] = [
  {
    slug: 'bioage',
    client: 'Roland Thomas',
    category: 'E-commerce',
    duration: '6+ Years',
    title: 'BIOAGE — Scaling a 7-Figure E-commerce Brand',
    subtitle: 'Long-Term Strategic Tech Partner',
    description: 'BIOAGE is a high-performing e-commerce brand generating 7-figure monthly revenue. For over 6 years, we have managed end-to-end technology, performance optimization, security, and continuous platform growth.',
    image: '/case-study/bioage-case-study.png',
    url: 'https://bioage.com',
    tech: ['WordPress', 'WooCommerce', 'SiteGround', 'Sucuri', 'Payment Gateways'],
    accentColor: 'teal',
    overview: 'BIOAGE is a premium natural microalgae supplement brand serving health-conscious consumers across Canada and the USA. Founded by Roland Thomas, the brand needed a robust, scalable e-commerce platform capable of handling high-volume sales while maintaining an exceptional user experience. Zalgo Infotech has been their exclusive technology partner since the very beginning — a partnership that has spanned over 6 years of continuous growth.',
    challenge: 'When Roland first approached us, BIOAGE had a basic WordPress site that was struggling to handle growing traffic, frequent plugin conflicts, and slow checkout experiences. Payment gateway failures during peak seasons were costing thousands in lost sales. Security vulnerabilities were a constant concern for a brand dealing with health products and customer payment data. The team needed a long-term partner — not a one-time developer.',
    solution: 'We performed a complete overhaul of the BIOAGE WordPress and WooCommerce stack. Starting with a server migration to SiteGround\'s enterprise hosting, we then rebuilt the checkout flow, integrated multiple payment gateways with failover support, and implemented Sucuri\'s enterprise firewall for airtight security. We set up automated daily backups, uptime monitoring, and a rapid-response support system. Over 6 years, we\'ve shipped hundreds of feature updates, seasonal campaigns, and performance improvements.',
    results: [
      { metric: '$1M+', label: 'Monthly Revenue Supported' },
      { metric: '6+', label: 'Years of Partnership' },
      { metric: '99.9%', label: 'Uptime Maintained' },
      { metric: '3×', label: 'Conversion Rate Improvement' },
    ],
    deliverables: [
      'Full WooCommerce store architecture & development',
      'Multi-gateway payment integration with failover',
      'Sucuri enterprise security & firewall setup',
      'SiteGround server migration & optimization',
      'Automated backups & disaster recovery plan',
      'Speed optimization — sub-2s page load times',
      'Ongoing monthly maintenance & updates',
      'Seasonal campaign landing pages',
    ],
    testimonial: {
      quote: 'Zalgo Infotech has been more than a development agency — they are a true business partner. For over 6 years, they have kept our platform running flawlessly while we focused on growing our brand. Their response time and technical expertise are unmatched.',
      name: 'Roland Thomas',
      role: 'Founder, BIOAGE',
    },
  },
  {
    slug: 'expert-heavy-equipment',
    client: 'Milissa',
    category: 'E-commerce',
    duration: '4+ Years',
    title: 'Expert Heavy Equipment — Website Redesign & Security Enhancement',
    subtitle: 'Security & Performance Overhaul',
    description: 'Expert Heavy Equipment is a trusted business in the heavy equipment industry. The client needed a strong, secure online presence to represent their brand and support long-term growth with integrated communication tools.',
    image: '/case-study/experthe-case-study.png',
    url: '#',
    tech: ['WordPress', 'WooCommerce', 'Twilio', 'Wordfence'],
    accentColor: 'orange',
    overview: 'Expert Heavy Equipment is a well-established business dealing in industrial and agricultural heavy machinery. With a growing client base across North America, Milissa needed a professional website that could showcase their equipment inventory, capture leads, and provide a secure communication channel for high-value B2B transactions. The old website was outdated, slow, and riddled with security gaps.',
    challenge: 'The existing website was built on an unmaintained WordPress theme with over 40 outdated plugins. The site had been compromised once before, resulting in injected malware that damaged their Google search rankings. Page load times exceeded 8 seconds, and the contact forms were unreliable — causing them to miss potential six-figure equipment deals. The client urgently needed a complete rebuild and a long-term security partner.',
    solution: 'We started with a full security audit and malware cleanup, then migrated the site to a hardened WordPress setup with Wordfence enterprise protection. The site was redesigned from scratch with a professional industrial aesthetic, fast-loading product pages, and a custom equipment inquiry system. We integrated Twilio for SMS notifications so Milissa\'s team receives instant alerts whenever a new lead comes in — no more missed opportunities. Monthly maintenance ensures the site stays secure and up-to-date.',
    results: [
      { metric: '4+', label: 'Years of Ongoing Support' },
      { metric: '0', label: 'Security Incidents Since Launch' },
      { metric: '5×', label: 'More Qualified Leads' },
      { metric: '<2s', label: 'Page Load Time' },
    ],
    deliverables: [
      'Complete WordPress website redesign',
      'Wordfence enterprise security setup',
      'Twilio SMS integration for lead alerts',
      'Custom equipment inquiry & quote system',
      'Malware removal & Google penalty recovery',
      'Speed optimization & caching setup',
      'Monthly maintenance & security monitoring',
      'SSL certificate & server hardening',
    ],
    testimonial: {
      quote: 'After our site was hacked, we were desperate for a reliable team. Zalgo Infotech not only fixed everything but built us a system that has never been compromised since. The Twilio integration alone has helped us close more deals than ever before.',
      name: 'Milissa',
      role: 'Owner, Expert Heavy Equipment',
    },
  },
  {
    slug: 'awakening-genius-within',
    client: 'Wellness Brand',
    category: 'Wellness',
    duration: 'Ongoing',
    title: 'Awakening The Genius Within — Book Showcase & Wellness Platform',
    subtitle: 'Wellness & Personal Development Website',
    description: 'A comprehensive informational website built on WordPress to showcase wellness and personal development resources — books, articles, and curated content empowering individuals to unlock their full potential.',
    image: '/case-study/Awakeningthegeniuswithin.jpg',
    url: 'https://awakeningthegeniuswithin.com',
    tech: ['WordPress', 'WooCommerce', 'CSS3', 'JavaScript', 'Responsive Design', 'SEO'],
    accentColor: 'purple',
    overview: 'Awakening The Genius Within is a personal development and wellness platform built around a series of transformational books and educational content. The brand needed a visually stunning WordPress website that could serve as both a book showcase and an ongoing content hub — attracting readers, selling books via WooCommerce, and building a loyal community of personal growth enthusiasts.',
    challenge: 'The client had a vision but no digital presence. They needed a website that matched the inspirational, premium feel of their brand — not a generic template. The site needed to sell books directly, host long-form articles, and be optimised for discovery through search engines. Previous developers had delivered a site that felt cold and corporate, completely mismatched with the warmth and energy of the brand.',
    solution: 'We designed and developed a custom WordPress website that perfectly captures the spirit of personal transformation. Elegant typography, warm colour gradients, and smooth scroll animations create an immersive experience. WooCommerce powers the book store with digital download support. A custom SEO content structure ensures every article ranks for high-intent wellness keywords. JavaScript-powered interactive elements keep users engaged throughout their journey on the site.',
    results: [
      { metric: '300%', label: 'Organic Traffic Growth' },
      { metric: '95', label: 'Google PageSpeed Score' },
      { metric: '4×', label: 'Book Sales Increase' },
      { metric: 'Ongoing', label: 'Content & SEO Support' },
    ],
    deliverables: [
      'Custom WordPress theme design & development',
      'WooCommerce book store with digital downloads',
      'SEO-optimised blog & content architecture',
      'Responsive design for all devices',
      'CSS3 & JavaScript animations',
      'Email newsletter integration',
      'Google Analytics & conversion tracking',
      'Ongoing SEO & content support',
    ],
  },
  {
    slug: 'dobramoc',
    client: 'E-commerce Brand',
    category: 'E-commerce',
    duration: 'Ongoing',
    title: 'Dobramoc — E-commerce Website Design & Development',
    subtitle: 'WooCommerce Store with Performance Optimization',
    description: 'A WooCommerce-powered e-commerce platform delivering a seamless online shopping experience with optimized performance, secure payment integration, and a conversion-focused product catalog.',
    image: '/case-study/Dobramoc.jpg',
    url: '#',
    tech: ['WordPress', 'WooCommerce', 'E-commerce', 'Payment Gateway', 'SEO', 'Responsive Design'],
    accentColor: 'blue',
    overview: 'Dobramoc is a growing e-commerce brand with a diverse product catalog targeting European markets. The brand needed a modern, high-performance WooCommerce store that could handle a large product inventory, multiple currencies, and a seamless checkout process. With a focus on organic SEO growth, the site needed to be technically perfect from the ground up.',
    challenge: 'The client was operating on an outdated e-commerce platform that couldn\'t scale with their growing catalog. Product pages were slow, the checkout had a high abandonment rate, and the site had no structured SEO foundation. Payment failures during high-traffic periods were eroding customer trust. A complete rebuild on WooCommerce was the only path forward.',
    solution: 'We architected a high-performance WooCommerce store built for scale. Custom product filtering, faceted search, and an optimised database structure ensure fast page loads even with thousands of products. We integrated multiple payment gateways with automatic retry logic to eliminate payment failures. A comprehensive SEO setup — including schema markup, XML sitemaps, and optimised product descriptions — drives consistent organic traffic growth month over month.',
    results: [
      { metric: '40%', label: 'Checkout Conversion Improvement' },
      { metric: '60%', label: 'Faster Page Load Times' },
      { metric: '200%', label: 'Organic Traffic Growth' },
      { metric: '0%', label: 'Payment Failure Rate' },
    ],
    deliverables: [
      'Custom WooCommerce store development',
      'Advanced product filtering & search',
      'Multi-gateway payment integration',
      'Database optimisation for large catalogs',
      'SEO foundation — schema, sitemaps, metadata',
      'Mobile-first responsive design',
      'Speed optimisation & caching',
      'Ongoing platform maintenance',
    ],
  },
  {
    slug: 'finance-manager-training',
    client: 'Finance Training Brand',
    category: 'Finance Training',
    duration: 'Ongoing',
    title: 'Finance Manager Training — Business Finance & Revenue Growth',
    subtitle: 'WooCommerce E-learning Platform for Finance Professionals',
    description: 'A WooCommerce-powered training platform delivering structured finance courses and revenue-growth strategies to business managers, scaled to $1M+ monthly revenue through targeted digital marketing.',
    image: '/case-study/Finance-Manager-Training.jpg',
    url: '#',
    tech: ['WordPress', 'WooCommerce', 'SEO', 'Digital Marketing', 'Responsive Design', 'Payment Gateway'],
    accentColor: 'yellow',
    overview: 'Finance Manager Training is a specialized e-learning platform serving business finance professionals across North America. The platform delivers structured, certification-ready finance courses to aspiring and current finance managers. What began as a small course website has grown — with Zalgo Infotech\'s technical support — into a $1M+ monthly revenue business through strategic platform development and digital marketing integration.',
    challenge: 'The client had valuable training content but a technically weak platform that couldn\'t handle the demands of a serious e-learning business. Course delivery was unreliable, payment processing was limited to a single gateway, and the site had no marketing integration. Student management was manual and time-consuming. Scaling beyond a few hundred students seemed impossible without a platform rebuild.',
    solution: 'We rebuilt the entire platform on WordPress with WooCommerce handling course sales, subscriptions, and student management. Custom course completion tracking, certificate generation, and student progress dashboards were developed to deliver a premium learning experience. We integrated advanced digital marketing tools — email automation, retargeting pixels, and SEO-optimised course landing pages — to fuel consistent student acquisition. The result: a self-sustaining platform that generates $1M+ monthly.',
    results: [
      { metric: '$1M+', label: 'Monthly Revenue Generated' },
      { metric: '5,000+', label: 'Students Enrolled' },
      { metric: '400%', label: 'Revenue Growth YoY' },
      { metric: 'Ongoing', label: 'Platform Development' },
    ],
    deliverables: [
      'Custom e-learning platform on WordPress',
      'WooCommerce course sales & subscriptions',
      'Student progress tracking & dashboards',
      'Automated certificate generation',
      'Email marketing & automation integration',
      'SEO-optimised course landing pages',
      'Multi-gateway payment processing',
      'Digital marketing pixels & tracking',
    ],
  },
  {
    slug: 'life-tree-anatomical',
    client: 'Healthcare Organisation',
    category: 'Healthcare',
    duration: 'Ongoing',
    title: 'Life Tree Anatomical — Whole Body Donation & Medical Research Service',
    subtitle: 'Healthcare-Focused Service Website',
    description: 'A healthcare-focused service website facilitating whole body donation for medical research and education. Provides individuals and families a clear, respectful, and guided anatomical donation process.',
    image: '/case-study/Lifetreeanatomical.jpg',
    url: 'https://lifetreeanatomical.com',
    tech: ['WordPress', 'Healthcare', 'UI/UX Design', 'JavaScript', 'CSS3', 'Responsive Design'],
    accentColor: 'green',
    overview: 'Life Tree Anatomical is a Texas-based healthcare organization facilitating the whole body donation process for medical research and anatomical education. Their mission is deeply personal and sensitive — helping individuals and families navigate a meaningful end-of-life decision with clarity, compassion, and dignity. The website needed to balance professionalism with warmth, making a complex medical process feel approachable and trustworthy.',
    challenge: 'Healthcare websites carry unique responsibilities — they must be accessible, empathetic, and compliant. The previous website was clinical and cold, failing to reflect the compassionate mission of the organisation. Important information about the donation process was buried and hard to find, leading to high bounce rates and low inquiry conversions. The client needed a site that felt like a supportive guide, not a medical form.',
    solution: 'We designed a completely custom WordPress experience with a warm, reassuring visual identity — soft greens, clean typography, and gentle animations that create a sense of calm and trust. The information architecture was rebuilt from the ground up: a step-by-step donation guide, FAQ sections, and clear CTAs guide families through the process without overwhelming them. JavaScript-powered interactive elements help users find the information they need quickly. Accessibility standards (WCAG) were strictly followed throughout.',
    results: [
      { metric: '250%', label: 'Inquiry Form Completions' },
      { metric: '70%', label: 'Bounce Rate Reduction' },
      { metric: 'WCAG', label: 'Accessibility Compliant' },
      { metric: 'Ongoing', label: 'Support & Maintenance' },
    ],
    deliverables: [
      'Custom WordPress website with empathetic design',
      'Step-by-step donation process guide',
      'WCAG accessibility compliance',
      'Interactive FAQ & resource sections',
      'Contact & inquiry system',
      'JavaScript UI enhancements',
      'Mobile-first responsive design',
      'Ongoing maintenance & content updates',
    ],
  },
  {
    slug: 'towels-outlet',
    client: 'Textile Brand',
    category: 'E-commerce',
    duration: 'Ongoing',
    title: 'Towels Outlet — Premium Textile E-commerce Store',
    subtitle: 'WooCommerce Store with Conversion-Focused Design',
    description: 'A WooCommerce-based online store for premium towels and textiles, built with a clean, conversion-focused design to drive online sales, enhance customer experience, and integrate seamless payment processing.',
    image: '/case-study/towelsoutlet.jpg',
    url: 'https://towelsoutlet.com',
    tech: ['WordPress', 'WooCommerce', 'E-commerce', 'SEO', 'Payment Gateway', 'Responsive Design'],
    accentColor: 'orange',
    overview: 'Towels Outlet is a premium online retailer specializing in high-quality towels, bathrobes, and textile accessories. With a broad product catalog and an audience that values quality and aesthetics, the brand needed an e-commerce experience that felt as premium as their products — clean, fast, and designed to convert browsers into buyers.',
    challenge: 'The brand was selling through a cluttered, visually inconsistent WooCommerce store that didn\'t reflect the premium quality of their products. Category pages were slow to load, product images weren\'t optimised, and the checkout process had too many friction points. The site was also missing basic SEO — product pages weren\'t ranking for any meaningful search terms, leaving significant organic revenue on the table.',
    solution: 'We redesigned the entire WooCommerce store with a clean, minimalist aesthetic that lets the products speak for themselves. High-quality product image galleries with zoom functionality, size/colour variant selectors, and a streamlined one-page checkout dramatically improved the buying experience. A comprehensive SEO strategy — optimised product titles, descriptions, and category pages — drove significant organic traffic growth. Payment gateway integration with multiple options (card, PayPal, buy-now-pay-later) removed barriers to purchase.',
    results: [
      { metric: '180%', label: 'Online Sales Increase' },
      { metric: '45%', label: 'Cart Abandonment Reduction' },
      { metric: '500%', label: 'Organic Traffic Growth' },
      { metric: 'Ongoing', label: 'SEO & Maintenance' },
    ],
    deliverables: [
      'Premium WooCommerce store redesign',
      'Advanced product image galleries',
      'Streamlined one-page checkout',
      'Multi-gateway payment integration',
      'Comprehensive SEO strategy & implementation',
      'Product page optimisation',
      'Mobile-first responsive design',
      'Ongoing SEO & store maintenance',
    ],
  },
  {
    slug: 'shivaline-plastotech',
    client: 'Shivaline Plastotech',
    category: 'Manufacturing',
    duration: '2 Months',
    title: 'Shivaline Plastotech — Industrial Website Development',
    subtitle: 'Building a Modern Digital Presence for Shivaline',
    description: 'Shivaline Plastotech is a leading industrial solutions and manufacturing company specializing in high-quality tarpaulin and cross-laminated film products for diverse industrial applications. Zalgo Infotech partnered with Shivaline to design and develop a modern, responsive corporate website that strengthens their digital presence and builds customer trust.',
    image: '/case-study/ZalgoinfotechShivalineMain.jpg',
    url: 'https://shivalineplastotech.com',
    tech: ['WordPress', 'Custom Theme', 'Responsive Design', 'SEO', 'UI/UX Design'],
    accentColor: 'blue',
    overview: 'Shivaline Plastotech is a leading industrial solutions and manufacturing company specializing in high-quality tarpaulin and cross-laminated film products for diverse industrial applications — from agriculture and construction to vehicle covers and sports field solutions. With a growing dealer network spanning 20+ states and international exports, Shivaline needed a professional corporate website capable of showcasing their manufacturing capabilities, product range, infrastructure, and distribution network to global B2B clients and distributors.',
    challenge: 'Shivaline is a leading industrial manufacturing brand specializing in woven tarpaulin, cross-laminated films, and protective covering solutions for multiple commercial and industrial applications. With growing market demand and an expanding product portfolio, the company required a stronger digital presence to showcase its capabilities professionally.\n\nBefore the website transformation, Shivaline faced significant challenges in presenting its products, manufacturing infrastructure, and brand credibility effectively online. The existing digital presence lacked modern design, structured product presentation, mobile responsiveness, and a user-focused experience needed to attract business inquiries and build trust with potential distributors and clients.\n\nAs the business continued to scale — with 175+ dealers, 20+ states presence, and international exports — Shivaline needed a professional corporate website capable of improving customer engagement, highlighting product categories, and strengthening the company\'s reputation in competitive industrial markets.',
    solution: 'Zalgo Infotech designed and developed a modern industrial website tailored to Shivaline\'s manufacturing business goals, product categories, and brand identity. The solution focused on creating a professional digital presence capable of improving customer trust, product visibility, and business credibility.\n\nWe implemented a clean and responsive UI/UX design that allows users to easily explore Shivaline\'s product range, manufacturing capabilities, infrastructure, and industrial applications across desktop and mobile devices. The website features structured product showcase pages, an infrastructure gallery, and a dedicated distribution network section highlighting their nationwide dealer presence and international reach.\n\nOur scalable WordPress solution enables Shivaline to continuously expand product categories, improve digital communication, and strengthen its reputation as a trusted industrial manufacturing brand in competitive global markets.',
    results: [
      { metric: '20+', label: 'States Presence Showcased' },
      { metric: '175+', label: 'Dealer & Distributor Network' },
      { metric: '90+', label: 'Development Hours' },
      { metric: '2', label: 'Expert Team Members' },
    ],
    deliverables: [
      'Responsive WordPress corporate website',
      'Mobile-optimized user experience',
      'Scalable CMS architecture',
      'Structured product showcase pages',
      'Infrastructure & facility gallery',
      'Distribution network & dealer map section',
      'Fast-loading performance optimization',
      'SEO-friendly content structure',
      'Secure website framework',
      'Easy content management system',
    ],
    highlights: [
      { label: 'Project Timeline', value: '2 Months', desc: 'End-to-end website planning, design, development, and optimization.' },
      { label: 'Development Hours', value: '90+ Hours', desc: 'Focused on responsive design, performance optimization, and SEO structure.' },
      { label: 'Dedicated Team', value: '2 Experts', desc: 'UI/UX design and development specialists collaborating for project delivery.' },
    ],
    gallery: [
      '/case-study/ZalgoinfotechShivaline.png',
      '/case-study/ZalgoinfotechShivaline2.png',
      '/case-study/ZalgoinfotechShivaline3.png',
      '/case-study/ZalgoinfotechShivaline4.png',
    ],
  },
  {
    slug: 'iparkhub',
    client: 'iParkHub',
    category: 'Technology',
    duration: 'Completed',
    title: 'iParkHub — Smart Parking Solutions Platform',
    subtitle: 'Modern Digital Platform for Automated Parking Management',
    description: 'iParkHub is an innovative smart parking solution platform focused on automated parking systems and modern parking management technologies. Zalgo Infotech designed and developed a professional digital platform to help the brand showcase its technology solutions, automation capabilities, and smart infrastructure services.',
    image: '/case-study/IParkMain.jpg',
    url: '#',
    tech: ['WordPress', 'Custom Theme', 'Responsive Design', 'SEO', 'UI/UX Design', 'JavaScript'],
    accentColor: 'yellow',
    overview: 'iParkHub is an innovative smart parking solution platform focused on automated parking systems and modern parking management technologies. Zalgo Infotech designed and developed a professional digital platform to help the brand showcase its technology solutions, automation capabilities, and smart infrastructure services.\n\nThe primary objective of the project was to create a responsive, scalable, and user-friendly website capable of presenting complex parking automation solutions in a clear and engaging way for businesses, property owners, and infrastructure stakeholders.\n\nBy developing a strong digital presence, iParkHub can now effectively communicate its smart parking technologies, improve customer engagement, and strengthen its credibility in the parking automation and infrastructure industry.',
    challenge: 'iParkHub required a modern digital platform capable of clearly presenting its smart parking technologies, automated parking systems, and infrastructure solutions to businesses, commercial properties, and urban development stakeholders.\n\nThe existing digital presentation lacked the structure and user experience needed to effectively explain complex parking automation services, showcase parking system types, and establish strong technological credibility in a competitive market.\n\nThe goal was to develop a professional, SEO-friendly, and conversion-focused website that strengthens iParkHub\'s digital presence while supporting future growth in the smart parking and automation industry.',
    solution: 'Zalgo Infotech designed and developed a modern technology-focused website tailored to iParkHub\'s smart parking and automated parking system solutions. The platform was structured to clearly communicate complex parking technologies through a clean, responsive, and user-friendly interface.\n\nWe implemented a scalable website architecture that organized parking solutions, automation services, and infrastructure capabilities into an easy-to-navigate digital experience for businesses, property developers, and commercial clients.\n\nOur solution helped iParkHub strengthen its digital presence, showcase its smart parking technologies more effectively, and establish stronger credibility within the parking automation and infrastructure industry.',
    results: [
      { metric: '2 Months', label: 'Development Timeline' },
      { metric: '90+', label: 'Development Hours' },
      { metric: '100%', label: 'Responsive Design' },
      { metric: 'SEO', label: 'Optimized Platform' },
    ],
    deliverables: [
      'Custom WordPress technology-focused website',
      'Responsive UI/UX design for all devices',
      'Structured parking solutions showcase pages',
      'Automation services & product catalog',
      'SEO-optimized content architecture',
      'Contact & inquiry system',
      'Fast-loading performance optimization',
      'Scalable CMS for easy content management',
    ],
    highlights: [
      { label: '2-Month Development Timeline', value: '2 Months', desc: 'Fast and efficient project execution with structured planning and agile delivery.' },
      { label: '90+ Development Hours', value: '90+', desc: 'Focused UI/UX design, responsive development, optimization, and project coordination workflows.' },
      { label: 'Dedicated Expert Team', value: 'Expert', desc: 'A specialized team handling design, development, optimization, and project coordination.' },
    ],
    gallery: [
      '/case-study/IPark1.png',
      '/case-study/IPark2.png',
      '/case-study/IPark3.png',
      '/case-study/IPark4.png',
    ],
  },
  {
    slug: 'indel-elevators',
    client: 'Indel Elevators',
    category: 'Manufacturing',
    duration: 'Completed',
    title: 'Indel Elevators — Advanced Elevator Solutions Website Development',
    subtitle: 'Professional Corporate Website for Vertical Mobility Solutions',
    description: 'Indel Elevators is a leading elevator solutions provider specializing in residential, commercial, industrial, and hospital elevator systems. The company required a modern digital platform to showcase its diverse product portfolio, strengthen brand credibility, and improve customer engagement.',
    image: '/case-study/IndelElevatorsMain.jpg',
    url: '#',
    tech: ['WordPress', 'Custom Theme', 'Responsive Design', 'SEO', 'UI/UX Design', 'Performance Optimization'],
    accentColor: 'blue',
    overview: 'Indel Elevators is a leading elevator solutions provider specializing in residential, commercial, industrial, and hospital elevator systems. With 37+ years of experience in the industry, Indel has served numerous prestigious clients and built a reputation for engineering excellence and quality. The company required a modern digital platform to showcase its diverse product portfolio, strengthen brand credibility, and improve customer engagement.\n\nZalgo Infotech designed and developed a responsive, user-friendly website that highlights Indel\'s advanced elevator solutions while delivering a seamless browsing experience across all devices. The platform was structured to improve product visibility, simplify customer inquiries, and support long-term business growth.\n\nFrom intuitive navigation and responsive layouts to performance optimization and scalable architecture, the project was developed to create a strong digital presence that reflects the company\'s engineering excellence and commitment to quality.',
    challenge: 'As a leading manufacturer of elevator and parking automation solutions, Indel Elevators required a digital platform that accurately reflected its engineering expertise and growing market presence.\n\nThe existing online experience lacked structured product presentation, clear service communication, and conversion-focused user journeys. Customers found it difficult to explore product categories, understand technical offerings, and submit inquiries efficiently.\n\nThe objective was to create a modern, responsive website that would improve product visibility, enhance user engagement, strengthen brand credibility, and generate qualified business inquiries while supporting long-term business expansion.',
    solution: 'To address Indel Elevators\' digital growth objectives, Zalgo Infotech designed and developed a modern, responsive website focused on user experience, product visibility, and lead generation. The platform was structured to present elevator products, maintenance services, and parking automation solutions through clear navigation and conversion-focused design.\n\nWe created dedicated sections for residential, commercial, industrial, and hospital elevator systems, enabling visitors to quickly explore solutions and submit inquiries. The website was optimized for mobile responsiveness, search engine visibility, performance, and accessibility across all devices.\n\nAdditionally, a scalable content structure was implemented to support future growth, showcase completed projects, highlight technical expertise, and strengthen the company\'s online credibility in the elevator and mobility solutions industry.',
    results: [
      { metric: '130+', label: 'Happy Clients' },
      { metric: '425+', label: 'Projects Handled' },
      { metric: '90+', label: 'Development Hours' },
      { metric: '37+', label: 'Years of Client Experience' },
    ],
    deliverables: [
      'Custom WordPress corporate website',
      'Dedicated product sections — Residential, Commercial, Industrial, Hospital',
      'Services showcase — Manufacturing, Installation, Maintenance, Consultancy',
      'Project portfolio & completed installations gallery',
      'Mobile-first responsive design',
      'SEO-optimized content architecture',
      'Performance & speed optimization',
      'Contact & inquiry system',
      'Scalable CMS for easy content updates',
      'WordPress CMS with SEO-friendly architecture',
    ],
    highlights: [
      { label: '8 Weeks Delivery Timeline', value: '8 Weeks', desc: 'From planning and design to development, testing, and deployment.' },
      { label: '90+ Development Hours', value: '90+', desc: 'Dedicated effort across UI/UX design, development, optimization, and quality assurance.' },
      { label: 'Dedicated Project Team', value: 'Expert', desc: 'Specialized professionals managing design, development, and implementation.' },
    ],
    gallery: [
      '/case-study/zalgoinfotech-indel01.png',
      '/case-study/zalgoinfotech-indel02.png',
      '/case-study/zalgoinfotech-indel03.png',
      '/case-study/zalgoinfotech-indel04.png',
      '/case-study/zalgoinfotech-indel05.png',
    ],
  },
  {
    slug: 'lockit-pro',
    client: 'LockIt Pro',
    category: 'Smart Security',
    duration: 'Completed',
    title: 'LockIt Pro — Smart Padlock Technology for Modern Security',
    subtitle: 'Professional Digital Platform for Smart Security Innovation',
    description: 'LockIt Pro is an innovative smart padlock solution designed to combine physical security with modern digital convenience. The product enables users to secure valuable assets while managing access through intelligent mobile-enabled technology.',
    image: '/case-study/LockItProMain.jpg',
    url: '#',
    tech: ['WordPress', 'Custom Theme Development', 'Responsive Web Design', 'HTML5 & CSS3', 'JavaScript', 'Mobile Optimization', 'SEO-Friendly Architecture', 'Performance Optimization'],
    accentColor: 'green',
    overview: 'LockIt Pro is an innovative smart padlock solution designed to combine physical security with modern digital convenience. The product enables users to secure valuable assets while managing access through intelligent mobile-enabled technology.\n\nZalgo Infotech partnered with LockIt Pro to create a professional digital platform that clearly communicates product features, security benefits, and technology advantages. The website was designed to showcase the smart locking ecosystem while delivering a seamless user experience across desktop and mobile devices.\n\nOur focus was on building a modern, conversion-oriented website that strengthens product credibility, highlights innovation, and helps potential customers understand how smart security solutions can simplify everyday protection and access management.',
    challenge: 'LockIt Pro introduced an innovative smart padlock solution that combined physical security with mobile technology. However, the brand needed a professional digital presence capable of clearly communicating its unique product features, technical advantages, and real-world applications to potential customers and partners.\n\nThe challenge was to present complex security technology in a simple and engaging way while building trust among users unfamiliar with smart locking systems. The existing digital experience lacked clear product storytelling, feature explanations, and conversion-focused content that could effectively demonstrate the product\'s value.\n\nAdditionally, the website needed to showcase key functionalities such as mobile app integration, remote access capabilities, durability, emergency backup systems, and intelligent security controls while maintaining a modern user experience across all devices.',
    solution: 'Zalgo Infotech created a modern, mobile-responsive website that highlights LockIt Pro\'s smart padlock technology through clear product presentation, feature-focused content, and intuitive navigation.\n\nThe platform showcases technical specifications, mobile app functionality, Bluetooth connectivity, and security benefits while providing a seamless user experience that strengthens credibility and supports customer acquisition.\n\nThe LockIt Pro website was developed to showcase smart security technology through an engaging and professional digital experience. The platform highlights product capabilities, mobile app integration, and technical specifications while delivering a seamless user journey across all devices — enhancing brand credibility and supporting business growth.',
    results: [
      { metric: '6', label: 'Weeks Delivery Timeline' },
      { metric: '120+', label: 'Estimated Man-Hours' },
      { metric: '3', label: 'Expert Team Members' },
      { metric: '100%', label: 'Mobile Responsive' },
    ],
    deliverables: [
      'Custom WordPress product showcase website',
      'Smart padlock product features & benefits pages',
      'Technical specifications display',
      'Mobile app integration showcase',
      'Bluetooth & connectivity feature presentation',
      'Responsive design across all devices',
      'SEO-friendly content architecture',
      'Performance & speed optimization',
      'Contact & inquiry system',
    ],
    highlights: [
      { label: '6 Weeks Delivery', value: '6 Weeks', desc: 'Fast and efficient project execution with structured planning and agile delivery.' },
      { label: '120+ Man-Hours', value: '120+', desc: 'Dedicated effort across UI/UX design, development, optimization, and quality assurance.' },
      { label: '3 Expert Team', value: '3 Experts', desc: 'Specialized professionals managing design, development, and implementation.' },
    ],
    gallery: [
      '/case-study/zalgoinfotech-lockitpro01.png',
      '/case-study/zalgoinfotech-lockitpro02.png',
      '/case-study/zalgoinfotech-lockitpro03.png',
      '/case-study/zalgoinfotech-lockitpro04.png',
      '/case-study/zalgoinfotech-lockitpro05.png',
    ],
  },
  {
    slug: 'kinein-medtech',
    client: 'Kinein MedTech',
    category: 'Healthcare Technology',
    duration: 'Completed',
    title: 'Kinein MedTech — Advanced Medical Device Solutions & OEM Healthcare Manufacturing',
    subtitle: 'Scalable Digital Platform for Global MedTech Products & Healthcare Education',
    description: 'Kinein MedTech is an advanced medical technology company specializing in orthopedic implants, surgical instruments, arthroscopy education, and OEM contract manufacturing. Zalgo Infotech designed and developed a professional digital platform to showcase their product portfolio and establish credibility in global healthcare markets.',
    image: '/case-study/KineinMain.png',
    url: '#',
    tech: ['WordPress', 'Custom Theme', 'Responsive Design', 'SEO', 'UI/UX Design', 'Performance Optimization'],
    accentColor: 'teal',
    overview: 'Kinein MedTech required a modern digital platform to showcase its innovative medical devices, arthroscopy education programs, and OEM contract manufacturing capabilities. The goal was to establish credibility in the healthcare industry while providing healthcare professionals and medical organizations with easy access to products, training resources, and company expertise.\n\nWe designed and developed a responsive healthcare website focused on user experience, product visibility, and lead generation. The platform highlights medical technology solutions, surgical training programs, orthopedic innovations, and contract manufacturing services through a clean, professional interface optimized for performance and search visibility.\n\nBy combining strategic content architecture, healthcare-focused design, and scalable web development, the website strengthens brand authority, improves engagement, and supports business growth within the medical technology sector.',
    challenge: 'Kinein MedTech needed a professional digital platform to showcase its growing portfolio of orthopedic implants, surgical instruments, and medical education initiatives while strengthening its presence in global healthcare markets. The existing challenge was presenting complex medical products, international events, and training programs in a clear and accessible manner for healthcare professionals, distributors, and industry partners.\n\nAdditionally, the company required an organized system to highlight upcoming medical conferences, educational workshops, and product innovations while maintaining a strong brand identity. The website also needed to support global visibility, improve user engagement, and provide seamless access to product information, helping Kinein MedTech connect with surgeons, healthcare institutions, and medical distributors worldwide.',
    solution: 'We developed a modern and scalable MedTech website that effectively showcases Kinein MedTech\'s extensive portfolio of orthopedic implants, surgical instruments, and healthcare solutions. The platform was structured to help healthcare professionals, distributors, and medical institutions easily explore product categories, technical information, and company expertise through an intuitive user experience.\n\nTo strengthen global reach and business growth, we implemented a streamlined product navigation system, responsive design, and strategically placed inquiry forms that simplify communication with potential partners and customers worldwide. The website also highlights Kinein MedTech\'s international presence, educational initiatives, and industry expertise, helping establish credibility across global healthcare markets.\n\nBy combining healthcare-focused design, optimized information architecture, and SEO-friendly development, the platform enhances product visibility, improves lead generation, and supports long-term digital growth in the competitive medical technology industry.',
    results: [
      { metric: '8', label: 'Weeks to Deliver' },
      { metric: '180+', label: 'Estimated Man-Hours' },
      { metric: '5', label: 'Experts Involved' },
      { metric: '1000+', label: 'Orthopedic Implants Listed' },
    ],
    highlights: [
      { label: 'Weeks', value: '8', desc: 'Project delivered in 8 weeks from brief to launch' },
      { label: 'Man-Hours', value: '180+', desc: 'Estimated effort across design, development & QA' },
      { label: 'Experts', value: '5', desc: 'Specialists including designers, developers & strategists' },
    ],
    deliverables: [
      'Full WordPress website design & development',
      'Orthopedic implant & surgical instrument product catalog',
      'OEM contract manufacturing capability showcase',
      'Arthroscopy education & training program pages',
      'Global medical events & conferences calendar',
      'Product category pages (Craniomaxillofacial, Shoulder, Spine, Sports Medicine, etc.)',
      'Certifications display (ISO 13485, ISO 9001, CE, GLP, GMP)',
      'International contact & inquiry system',
      'SEO-optimized architecture for healthcare & medical device keywords',
    ],
    gallery: [
      '/case-study/zalgoinfotech-kineinmedtech.png',
      '/case-study/zalgoinfotech-kineinmedtech01.png',
      '/case-study/zalgoinfotech-kineinmedtech02.png',
      '/case-study/zalgoinfotech-kineinmedtech03.png',
      '/case-study/zalgoinfotech-kineinmedtech04.png',
    ],
  },
  {
    slug: 'leomi',
    client: 'LEOMI',
    category: 'Industrial Technology',
    duration: 'Completed',
    title: 'LEOMI — Insertion Thermal Mass Flow Meter | German Technology Engineered in India',
    subtitle: 'Precision Engineering Digital Platform for Industrial Flow Measurement Solutions',
    description: 'LEOMI is a manufacturing venture specializing in Thermal Mass Flow Meters with German engineering standards, providing industrial measurement solutions for manufacturing, oil & gas, energy, water treatment, and process industries. Zalgo Infotech designed and developed a professional platform to showcase their product range and technical expertise.',
    image: '/case-study/LeomiMain.png',
    url: '#',
    tech: ['WordPress', 'Custom Theme', 'Responsive Design', 'SEO', 'UI/UX Design', 'Performance Optimization'],
    accentColor: 'blue',
    overview: 'LEOMI required a modern digital platform to showcase its industrial flow meters, process instrumentation solutions, and engineering expertise to customers across manufacturing, oil & gas, energy, water treatment, and process industries. The objective was to strengthen brand credibility, improve product visibility, and simplify access to technical information for engineers, consultants, and industrial buyers.\n\nWe designed and developed a responsive WordPress website focused on product discovery, technical communication, and lead generation. The platform effectively highlights flow measurement technologies, industrial automation solutions, and engineering capabilities through a clean user experience and structured information architecture.\n\nBy combining performance-driven web development, SEO-friendly content strategy, and intuitive navigation, the website helps LEOMI increase online visibility, attract qualified industrial inquiries, and establish a stronger digital presence in the competitive industrial instrumentation market.',
    challenge: 'LEOMI specializes in industrial flow measurement, process instrumentation, and automation solutions for critical industries. The challenge was to present highly technical concepts such as thermal mass flow measurement, gas monitoring systems, and industrial instrumentation in a way that engineers and decision-makers could easily understand.\n\nThe website needed to clearly communicate product capabilities, measurement principles, industry applications, and technical advantages while maintaining a professional and user-friendly experience. Additionally, improving visibility for industrial automation and flow meter-related search terms was essential to attract qualified B2B leads.\n\nA strategic combination of technical content, SEO optimization, and intuitive navigation was implemented to simplify complex information, strengthen brand credibility, and support lead generation across industrial sectors.',
    solution: 'LEOMI required a platform that could effectively showcase industry insights, technical publications, product innovations, and engineering expertise. The solution focused on creating a structured content ecosystem that highlights flow measurement technologies, industrial applications, research articles, and media features in an accessible and elegant format.\n\nBy organizing technical resources, case studies, and knowledge-sharing content into a user-friendly interface, the website strengthens thought leadership and helps industrial professionals make informed decisions. The improved content architecture also enhances search visibility, user engagement, and lead generation opportunities across manufacturing, energy, process, and automation industries.\n\nLEOMI has established itself as a trusted provider of advanced flow measurement and industrial instrumentation solutions. Through a structured user experience, detailed product information, and comprehensive technical resources, the platform helps engineers, plant operators, and decision-makers quickly access the information they need — reinforcing LEOMI\'s position as a leader in industrial automation and process measurement.',
    results: [
      { metric: '3', label: 'Months to Deliver' },
      { metric: '180+', label: 'Estimated Man-Hours' },
      { metric: '4', label: 'Experts Involved' },
      { metric: 'ISO', label: '9001:2015 Certified' },
    ],
    highlights: [
      { label: 'Duration', value: '3 Months', desc: 'Project delivered in 3 months from brief to launch' },
      { label: 'Man-Hours', value: '180+', desc: 'Estimated effort across design, development & QA' },
      { label: 'Experts', value: '4', desc: 'Specialists including designers, developers & strategists' },
    ],
    deliverables: [
      'Full WordPress website design & development',
      'LEOMI 581 Thermal Mass Flowmeter product showcase',
      'Technical specifications & measurement principle pages',
      'Industry application pages (Manufacturing, Oil & Gas, Energy, Water Treatment)',
      'News & articles content ecosystem with technical publications',
      'Media publications & thought leadership section',
      'FAQ section for industrial buyer queries',
      'ISO 9001:2015 certification & compliance display',
      'SEO-optimized architecture for industrial measurement keywords',
    ],
    gallery: [
      '/case-study/zalgoinfotech-leomi01.png',
      '/case-study/zalgoinfotech-leomi02.png',
      '/case-study/zalgoinfotech-leomi03.png',
      '/case-study/zalgoinfotech-leomi04.png',
      '/case-study/zalgoinfotech-leomi05.png',
    ],
  },
  {
    slug: 'compufy-technolab',
    client: 'Compufy Technolab',
    category: 'IT Consulting',
    duration: 'Completed',
    title: 'Compufy Technolab — Modern IT Solutions Website Designed for Growth & Trust',
    subtitle: 'Professional Digital Platform for IT Consulting & Technology Services',
    description: 'Compufy Technolab is a technology-driven company providing IT consulting, managed IT services, cybersecurity solutions, cloud services, and digital transformation support for businesses. Zalgo Infotech redesigned and developed a professional, user-focused website that highlights their expertise and builds trust with potential clients.',
    image: '/case-study/CompufyMain.jpg',
    url: '#',
    tech: ['WordPress', 'Custom Theme Development', 'Responsive Web Design', 'Performance Optimization', 'Mobile-First Development', 'SEO-Friendly Architecture'],
    accentColor: 'blue',
    overview: 'Compufy Technolab is a technology-driven company providing IT consulting, managed IT services, cybersecurity solutions, cloud services, and digital transformation support for businesses. Their goal was to create a modern digital presence that clearly communicates their expertise while building trust with potential clients.\n\nZalgo Infotech redesigned and developed a professional, user-focused website that highlights Compufy\'s service offerings, industry experience, and customer success stories. The new platform features a clean interface, intuitive navigation, responsive design, and conversion-focused user journeys that help visitors quickly understand services and connect with the team.\n\nThe result is a scalable and visually engaging website that strengthens brand credibility, improves user experience, and supports lead generation across multiple business sectors.',
    challenge: 'As a growing IT consulting and technology solutions provider, Compufy Technolab needed a digital presence that could effectively communicate its diverse service portfolio while establishing credibility in a highly competitive market. The existing presentation lacked a structured approach to showcase expertise across cloud consulting, cybersecurity, DevOps, database management, and staff augmentation services.\n\nThe challenge was to create a professional platform that clearly explained complex technical solutions, highlighted industry experience, and built trust among enterprise clients and decision-makers. Additionally, the website needed to improve user engagement, simplify service discovery, and encourage potential customers to connect with the team for consultations and project inquiries.\n\nA scalable, responsive, and conversion-focused digital experience was essential to support future growth, strengthen brand positioning, and generate qualified business opportunities.',
    solution: 'To address Compufy Technolab\'s business goals, we designed and developed a modern, service-focused digital platform that effectively showcases their expertise across cloud consulting, cybersecurity, DevOps, database management, and staff augmentation services. The website architecture was structured to simplify complex technical offerings while providing visitors with a clear understanding of the company\'s capabilities and value proposition.\n\nOur team implemented an intuitive user experience, responsive design, optimized navigation, and conversion-focused layouts to improve engagement and lead generation. Dedicated service pages, trust-building elements, industry-focused solutions, and clear call-to-action sections were strategically integrated to guide potential clients through their decision-making journey.\n\nThe final solution delivers a scalable and professional online presence that strengthens brand credibility, improves service visibility, enhances user experience, and supports Compufy Technolab\'s long-term business growth objectives.',
    results: [
      { metric: '6', label: 'Weeks to Deliver' },
      { metric: '120+', label: 'Development Hours' },
      { metric: '3', label: 'Project Specialists' },
      { metric: '100%', label: 'Mobile Responsive' },
    ],
    highlights: [
      { label: 'Weeks', value: '6', desc: 'Project delivered in 6 weeks from brief to launch' },
      { label: 'Dev Hours', value: '120+', desc: 'Estimated development hours across design and build' },
      { label: 'Specialists', value: '3', desc: 'Project specialists including designers and developers' },
    ],
    deliverables: [
      'Full website redesign & development on WordPress',
      'Cloud consulting, cybersecurity & DevOps service pages',
      'Database management & staff augmentation showcases',
      'Industry-focused solutions architecture',
      'Conversion-focused layouts with clear CTAs',
      'Responsive mobile-first design across all devices',
      'Performance optimization for fast loading speeds',
      'SEO-friendly architecture for organic discovery',
      'Trust-building elements & customer success stories',
    ],
    gallery: [
      '/case-study/compufytechnolab01.png',
      '/case-study/compufytechnolab02.png',
      '/case-study/compufytechnolab03.png',
      '/case-study/compufytechnolab04.png',
      '/case-study/compufytechnolab05.png',
    ],
  },
  {
    slug: 'kalp-mantra',
    client: 'Kalp Mantra',
    category: 'Ayurvedic Healthcare',
    duration: 'Completed',
    title: 'Kalp Mantra — Building a Trusted Digital Presence for Ayurvedic Healthcare',
    subtitle: 'Patient-Focused Healthcare Website for Ayurvedic Treatments & Wellness Products',
    description: 'Kalp Mantra is an Ayurvedic healthcare and wellness brand dedicated to providing natural solutions for kidney, gallbladder, and other health concerns through traditional Ayurvedic treatments. Zalgo Infotech designed and developed a modern, patient-focused website that builds trust, educates patients, and simplifies appointment booking.',
    image: '/case-study/KalpMantraMain.jpg',
    url: '#',
    tech: ['WordPress', 'WooCommerce', 'Custom Theme', 'Responsive Design', 'SEO', 'UI/UX Design'],
    accentColor: 'teal',
    overview: 'Kalp Mantra is an Ayurvedic healthcare and wellness brand dedicated to providing natural solutions for kidney, gallbladder, and other health concerns through traditional Ayurvedic treatments. The brand required a professional digital platform that would build trust, educate patients, and simplify appointment booking while showcasing its certifications, products, and healthcare expertise.\n\nZalgo Infotech designed and developed a modern, patient-focused website that combines credibility, accessibility, and user-friendly navigation. The platform highlights treatment information, product offerings, certifications, testimonials, and consultation options through a clean and responsive interface optimized for all devices.\n\nThe result is a trustworthy digital experience that strengthens brand authority, improves patient engagement, increases online visibility, and provides a scalable foundation for long-term business growth in the healthcare and wellness industry.',
    challenge: 'Kalp Mantra needed a professional healthcare website capable of building patient trust, showcasing Ayurvedic treatments, and educating visitors about natural wellness solutions. The challenge was to simplify complex healthcare information, improve online visibility, highlight certifications and treatment expertise, and create a seamless user experience that encourages consultation requests and patient engagement.\n\nThe client required a platform that could effectively present kidney stone, gallbladder stone, liver, digestion, and urinary treatment programs in an accessible and medically credible format. Building confidence among patients seeking natural alternatives to conventional medicine demanded a design that balanced authority with approachability.\n\nAdditionally, the website needed to support WooCommerce-powered product sales, mobile responsiveness, and SEO optimization to reach patients searching for Ayurvedic treatment options across India.',
    solution: 'Our solution focused on transforming Kalp Mantra\'s digital storefront into a reliable platform for Ayurvedic healthcare products and wellness solutions. We designed an intuitive product ecosystem that allows visitors to easily browse treatments, compare products, and access detailed information needed to make informed health decisions.\n\nThe website features organized product categories, responsive layouts, secure user interactions, and optimized performance across all devices. By integrating healthcare-focused user experience principles with scalable website architecture, we created a platform that strengthens customer confidence, enhances online visibility, and supports sustainable business growth through improved product discoverability and engagement.\n\nKalp Mantra required a digital platform that could effectively showcase Ayurvedic treatments, patient success stories, healthcare expertise, and wellness products while building trust among prospective patients. We developed a modern WordPress-based website focused on credibility, user engagement, and seamless navigation that helps Kalp Mantra strengthen its online presence and improve patient inquiries.',
    results: [
      { metric: '6', label: 'Weeks to Deliver' },
      { metric: '140+', label: 'Estimated Man-Hours' },
      { metric: '4', label: 'Experts Involved' },
      { metric: '100%', label: 'Mobile Responsive' },
    ],
    highlights: [
      { label: 'Weeks', value: '6', desc: 'Project delivered in 6 weeks from brief to launch' },
      { label: 'Man-Hours', value: '140+', desc: 'Estimated effort across design, development & QA' },
      { label: 'Experts', value: '4', desc: 'Specialists including designers, developers & strategists' },
    ],
    deliverables: [
      'Full WordPress + WooCommerce website design & development',
      'Ayurvedic treatment pages (Kidney, Gallbladder, Liver, Digestion, Urinary)',
      'Product catalog with detailed descriptions & pricing',
      'Patient results & success story showcase sections',
      'Certifications display (FSSAI, GMP, ISO 9001:2015)',
      'Appointment booking & free consultation flow',
      'FAQ section for patient queries',
      'Responsive mobile-first design across all devices',
      'SEO-optimized architecture for Ayurvedic healthcare keywords',
    ],
    gallery: [
      '/case-study/zalgoinfotech-kalpmantra01.png',
      '/case-study/zalgoinfotech-kalpmantra02.png',
      '/case-study/zalgoinfotech-kalpmantra03.png',
      '/case-study/zalgoinfotech-kalpmantra04.png',
      '/case-study/zalgoinfotech-kalpmantra05.png',
    ],
  },
  {
    slug: 'the-buzz-app',
    client: 'The Buzz App',
    category: 'Smart Home / IoT',
    duration: 'Completed',
    title: 'The Buzz App — Controlling Smart Devices Through a Single Mobile Experience',
    subtitle: 'Modern Digital Platform for Smart Home Automation & IoT Connectivity',
    description: 'The Buzz App is an innovative smart home automation platform designed to simplify the way users interact with connected devices. Through a centralized mobile application, users can monitor, manage, and control compatible smart devices from anywhere, creating a more convenient, secure, and connected living environment.',
    image: '/case-study/BuzzMain.jpg',
    url: '#',
    tech: ['WordPress', 'Custom Theme Development', 'Responsive Web Design', 'Performance Optimization', 'Mobile-First Development', 'SEO-Friendly Architecture'],
    accentColor: 'orange',
    overview: 'The Buzz App is an innovative smart home automation platform designed to simplify the way users interact with connected devices. Through a centralized mobile application, users can monitor, manage, and control compatible smart devices from anywhere, creating a more convenient, secure, and connected living environment.\n\nZalgo Infotech partnered with The Buzz App team to develop a modern digital platform that clearly communicates the product\'s capabilities, user benefits, and technology ecosystem. Our objective was to create an engaging user experience that demonstrates how smart automation can improve everyday life while maintaining simplicity and accessibility for users of all technical backgrounds.\n\nThe final solution showcases the platform\'s smart device integration, mobile connectivity, automation features, and intuitive controls through a responsive, user-friendly website designed to support product adoption, customer engagement, and long-term business growth.',
    challenge: 'The Buzz App was created to solve a common everyday problem — misplaced personal belongings and limited visibility into connected smart devices. While the product offered innovative Bluetooth tracking and proximity-based assistance, the challenge was presenting these advanced features in a simple, intuitive, and user-friendly manner for a broad audience.\n\nThe client required a digital platform that could effectively communicate the value of smart tracking technology, demonstrate real-world use cases, and build trust among potential users. Explaining device connectivity, location tracking, mobile integration, and smart alerts without overwhelming visitors was a key challenge.\n\nAdditionally, the website needed to highlight product benefits, improve user engagement, support product adoption, and provide a seamless experience across desktop and mobile devices while maintaining a modern and technology-focused brand identity.',
    solution: 'To address the client\'s requirements, Zalgo Infotech designed and developed a modern digital platform that clearly demonstrates how The Buzz App simplifies everyday life through smart connectivity and intelligent device interaction. Our goal was to transform complex IoT functionality into an engaging user experience that users could instantly understand and trust.\n\nWe created a clean, user-focused website that showcases the product\'s core capabilities, including Bluetooth connectivity, smart widget controls, proximity tracking, item-finding assistance, and mobile app integration. Through intuitive layouts, interactive visuals, and strategically structured content, visitors can quickly understand the product\'s benefits and real-world applications.\n\nThe final solution delivers a responsive, high-performance digital experience that strengthens product credibility, improves customer engagement, and supports business growth by effectively communicating The Buzz App\'s unique value proposition.',
    results: [
      { metric: '8', label: 'Weeks to Deliver' },
      { metric: '160+', label: 'Estimated Man-Hours' },
      { metric: '4', label: 'Experts Involved' },
      { metric: '100%', label: 'Mobile Responsive' },
    ],
    highlights: [
      { label: 'Weeks', value: '8', desc: 'Project delivered in 8 weeks from brief to launch' },
      { label: 'Man-Hours', value: '160+', desc: 'Estimated effort across design, development & QA' },
      { label: 'Experts', value: '4', desc: 'Specialists including designers, developers & strategists' },
    ],
    deliverables: [
      'Smart home automation platform website design & development',
      'Bluetooth connectivity & IoT device feature showcase',
      'Proximity tracking & item-finding feature presentation',
      'Mobile app integration & smart widget controls display',
      'Responsive mobile-first design across all devices',
      'WordPress CMS with custom theme development',
      'Performance optimization for fast page loads',
      'SEO-friendly architecture for organic discovery',
      'Product storytelling & user engagement flows',
    ],
    gallery: [
      '/case-study/zalgoinfotech-thebuzzapp.png',
      '/case-study/zalgoinfotech-thebuzzapp02.png',
      '/case-study/zalgoinfotech-thebuzzapp03.png',
      '/case-study/zalgoinfotech-thebuzzapp04.png',
      '/case-study/zalgoinfotech-thebuzzapp05.png',
    ],
  },
];

export function getCaseStudy(slug: string): CaseStudy | undefined {
  return caseStudies.find(cs => cs.slug === slug);
}
